### PR TITLE
Added docs to repo with grunt build process

### PR DESCRIPTION
**Pull request by chill117**
Ready!

To-do:
* [x] Add syntax highlighting; [prismjs](http://prismjs.com/)
* [x] Add nav search functionality
* [x] Hierarchical nav; ~~with only the first level nav items visible by default.~~
* [x] Fix indentation in code blocks

### CODE REVIEW

**Comment by chill117** [comment]
@kumilingus Ready for review!

**Comment by kumilingus** [comment]
There is something wrong with the indentation inside the code blocks.
image

**Comment by chill117** [comment]
> There is something wrong with the indentation inside the code blocks.

Okie dokie. I'll try to figure it out.

**Comment by chill117** [comment]
@kumilingus Ready!

**Comment by chill117** [comment]
@kumilingus Ready, again!

**Comment by kumilingus** [comment]
* [ ] remove character entities from code blocks

image

* [ ] fix links `dia.Element.getBBox` -> `dia.Element.prototype.getBBox` and  `dia.Paper.cellViewNamespace` -> `dia.Paper.options.cellViewNamespace`.

**Comment by kumilingus** [comment]
👍

**Pull request merged**
