### PR TITLE
Compiled lodash templates

### PR DESCRIPTION
**Pull request by automagic**
The use of the lodash function _.template violates modern browser Content Security Policy (CSP) 'unsafe-eval'.   See https://github.com/lodash/lodash/issues/832

This pull request removes _.template calls in favor of precompiling the templates using a grunt task and including them in the build.  

We wanted to float this idea and get some feedback

### CODE REVIEW

**Comment by mike-goodwin** [comment]
Is there any plan to merge this into master? It would be nice to remove unsafe-eval...

**Comment by chill117** [comment]
There might be more changes needed to make jointjs work well with CSP. I'll add this to my to-do list.

**Comment by chill117** [comment]
@mike-goodwin I've updated jointjs with fixes that will allow you to use the content-security-policy header  without unsafe-eval. These changes will be included in the next jointjs release (0.9.8). Here's the CSP header that will work with jointjs:
```
add_header Content-Security-Policy "default-src 'self'; img-src 'self' data:;";
```

**Comment by mike-goodwin** [comment]
@chill117 : Thank you - I'll upgrade to 0.9.8 as soon as it is released!

**Pull request closed without merging**
