### PR TITLE
Fix typescript --noImplicitAny errors

### LINKED ISSUE #575: Errors with TypeScript `--noImplicitAny`
To verify:

```sh
cd dist
tsc --noImplicitAny joint.d.ts
```

This can be fixed by adding type annotations in all the places the compiler gives you errors.
We'd like to deprecate `@types/jointjs` and just use `joint` (DefinitelyTyped/DefinitelyTyped#15561), but can't do that yet as we get `--noImplicitAny` errors in packages that depend on it.

### PR DESCRIPTION
**Pull request by CaselIT**
I've fixed the last implicit any errors in the `geometry.d.ts` file and updated the complete `joint.d.ts` file in the dist folder.

This pr closes #575

### CODE REVIEW

**Comment by CaselIT** [comment]
@vtalas I've removed the changes to `dist`

**Comment by andy-ms** [comment]
These changes still need to be published.

**Comment by kumilingus** [comment]
It's published now (`dist` folder on master branch).

**Comment by CaselIT** [comment]
I think @andy-ms meant to the npm repository

**Comment by kumilingus** [comment]
You can install npm package directly from the JointJS repository (`"git+https://github.com/clientIO/joint.git"`) . We'll publish to the npm repository when `v1.1.1` is finished.

**Pull request merged**
