### PR TITLE
add LinkView supp for findView and findViewByModel

### PR DESCRIPTION
**Pull request by mahald**
added missing Link/LinkView support for paper.findView and
paper.findViewByModel

### CODE REVIEW

**Comment by kumilingus** [comment]
How about the `Element`/`ElementView`? Both `Element` and `Link` inherit from `Cell`. Is this necessary? Thanks.

**Comment by mahald** [comment]
ok it's wrong anyways, it would have to be: "ElementView | LinkView".

imho if using typescript it should return precise types and not kinda base class. 
for sure u can cast it but then u as good could use any as type.

currently i have to do it as follows:
`
this.graph.on('change:position', function(cell) {
    let links: joint.dia.Link[] = this.graph.getLinks()
	for (let i = 0; i < links.length; i++) {
        let x = paper.findViewByModel(links[i]) as joint.dia.LinkView
        x.update(null, null);
	};
}.bind(this));
`

i would prefer:
`paper.findViewByModel<joint.dia.LinkView>(links[i]).update(null, null); `
instead

the big advantage in the second case is, the editor is going to tell me what types are possible (intelli Sense). In the first case i got to consult the manual or guess it.

just my 2 cents

**Comment by kumilingus** [comment]
It makes totally sense to me. If you can explicitly add both `ElementView` and `LinkView` to the definition I am happy to merge this. Thank You.

**Comment by mahald** [comment]
Ok updated.

**Comment by kumilingus** [comment]
Thanks!

**Pull request merged**
