### PR TITLE
TS def: typescript definition cleanup 

### PR DESCRIPTION
**Pull request by vtalas**
remove private methods from definition files 
- [x]  CellViewGeneric
- [x] CellView
- [x] ElementView
- [x] dia.Link
- [x] dia.Element 
- [x] dia.Paper
- [x] dia.Graph

### CODE REVIEW

**Comment by ChrisMoran** [comment]
Don't you need some of these methods defined if you wanted to extend this class in typescript?

**Comment by ChrisMoran** [comment]
To clarify what I mean, say you wanted to create a custom Element and ElementView like:

```
class CustomElement extends ElementView {
  markup = '<rect class="regular"/><rect class="special"/>'
  ...
}

class CustomElementView extends ElementView {
  mouseover: (evt: Event) => {
    if (evt.target.classList.contains('special')) {
      this.notify('cell:mouseoverspecial', evt);
    } else {
      super.mouseover(evt);
    }
  }
}
```

Now the Typescript compiler wouldn't see the mouseover method on ElementView, and the above wouldn't compile.

**Comment by vtalas** [comment]
oh yes, good point! it totally makes sense leave these there, check out my latest updates, `protected` could be the right way, what do you think?

**Comment by ChrisMoran** [comment]
Protected makes much more sense, thanks for updating! This change 👍

**Pull request merged**
