### PR TITLE
feat(dia.CellView)!: separate alias and calc expression evaluation fro…

### PR DESCRIPTION
**Pull request by kumilingus**
TBD

image

### CODE REVIEW

**Comment by kumilingus** [comment]
Currently, it allows you to switch off the support for camel-case. But if we move the alias logic to `Vectorizer.attr()` it would solve #1421.

**Comment by kumilingus** [comment]
At this point, I'm not sure if it's worth optimizing. See https://jsperf.app/disifi.

**Comment by alexandernst** [comment]
🤔 it’s 11% slower on iPhone 12 mini, but indeed I don’t think it will really matter that much on desktop. Maybe on batch operations where multiple attrs of multiple cells will be modified?

**Comment by kumilingus** [comment]
Obsolete now. See https://github.com/clientIO/joint/pull/2459.

**Pull request closed without merging**
