### PR TITLE
Issue #215: Improve grunt build tasks and add `grunt dist`

### PR DESCRIPTION
**Pull request by chill117**

### CODE REVIEW

**Comment by kumilingus** [comment]
Looks good.
1. Please rebase.
2. Could you update `README.md`?

**Comment by chill117** [comment]
> 1. Please rebase.

There are merge commits. Are you sure about that?

**Comment by kumilingus** [comment]
| There are merge commits. Are you sure about that?
Positive. There are merge commits with master. Rebase against master. `git rebase upstream/master`

**Comment by chill117** [comment]
@kumilingus All set ;)

**Comment by kumilingus** [comment]
Is `build:dist` in `README.md`?

**Comment by chill117** [comment]
> Is grunt dist in README.md?

It does now :)

**Comment by kumilingus** [comment]
Nice!

**Pull request merged**
